openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions


logging:
  level:
    com.github.wenqiglantz.service.openaiclient: TRACE

spring:
  jackson:
    default-property-inclusion: NON_NULL